version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: myapp_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PGSQL_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - myapp
  dbadmin:
    image: dpage/pgadmin4:latest
    container_name: myapp_pgadmin
    ports:
      - ${DB_ADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DB_ADMIN_PASS}
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - myapp
  php:
    container_name: myapp_php
    depends_on:
      - db
    build:
      context: ./php/
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./app/:${APP_PATH}
    networks:
      - myapp
  nginx:
    container_name: myapp_nginx
    depends_on:
      - php
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_PORT_TLS}:443
    networks:
      - myapp

networks:
  myapp:


volumes:
  db-data:
